name: Ubuntu CI

on:
  pull_request:
  push:
    branches:
      - 'ign-transport[0-9]?'
      - 'gz-transport[0-9]?'
      - 'main'

jobs:
  noble-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Noble CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile and test
        id: ci
        uses: gazebo-tooling/action-gz-ci@noble
        with:
          # codecov-enabled: true
          cppcheck-enabled: true
          cpplint-enabled: true
          doxygen-enabled: true
          cmake-args: '-DGZ_TRANSPORT_ENABLE_ZENOH=OFF'
  noble-ci-zenoh:
    runs-on: ubuntu-latest
    name: Ubuntu Noble CI - Zenoh
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile and test
        id: ci
        uses: gazebo-tooling/action-gz-ci@noble
        with:
          cmake-args: '-DGZ_TRANSPORT_DEFAULT_IMPLEMENTATION=zenoh'
